// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: queue/internal_queue.proto

package queue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InternalQueueService_UpdateQueueStateToDrained_FullMethodName = "/cloudidl.queue.InternalQueueService/UpdateQueueStateToDrained"
)

// InternalQueueServiceClient is the client API for InternalQueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalQueueServiceClient interface {
	// When queue is drained in leasor service, it should call this endpoint to update queue state to DRAINED.
	UpdateQueueStateToDrained(ctx context.Context, in *UpdateQueueStateToDrainedRequest, opts ...grpc.CallOption) (*UpdateQueueStateToDrainedResponse, error)
}

type internalQueueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalQueueServiceClient(cc grpc.ClientConnInterface) InternalQueueServiceClient {
	return &internalQueueServiceClient{cc}
}

func (c *internalQueueServiceClient) UpdateQueueStateToDrained(ctx context.Context, in *UpdateQueueStateToDrainedRequest, opts ...grpc.CallOption) (*UpdateQueueStateToDrainedResponse, error) {
	out := new(UpdateQueueStateToDrainedResponse)
	err := c.cc.Invoke(ctx, InternalQueueService_UpdateQueueStateToDrained_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalQueueServiceServer is the server API for InternalQueueService service.
// All implementations should embed UnimplementedInternalQueueServiceServer
// for forward compatibility
type InternalQueueServiceServer interface {
	// When queue is drained in leasor service, it should call this endpoint to update queue state to DRAINED.
	UpdateQueueStateToDrained(context.Context, *UpdateQueueStateToDrainedRequest) (*UpdateQueueStateToDrainedResponse, error)
}

// UnimplementedInternalQueueServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInternalQueueServiceServer struct {
}

func (UnimplementedInternalQueueServiceServer) UpdateQueueStateToDrained(context.Context, *UpdateQueueStateToDrainedRequest) (*UpdateQueueStateToDrainedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQueueStateToDrained not implemented")
}

// UnsafeInternalQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalQueueServiceServer will
// result in compilation errors.
type UnsafeInternalQueueServiceServer interface {
	mustEmbedUnimplementedInternalQueueServiceServer()
}

func RegisterInternalQueueServiceServer(s grpc.ServiceRegistrar, srv InternalQueueServiceServer) {
	s.RegisterService(&InternalQueueService_ServiceDesc, srv)
}

func _InternalQueueService_UpdateQueueStateToDrained_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQueueStateToDrainedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalQueueServiceServer).UpdateQueueStateToDrained(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalQueueService_UpdateQueueStateToDrained_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalQueueServiceServer).UpdateQueueStateToDrained(ctx, req.(*UpdateQueueStateToDrainedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalQueueService_ServiceDesc is the grpc.ServiceDesc for InternalQueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalQueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudidl.queue.InternalQueueService",
	HandlerType: (*InternalQueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateQueueStateToDrained",
			Handler:    _InternalQueueService_UpdateQueueStateToDrained_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queue/internal_queue.proto",
}

const (
	InternalQueueManagerService_WatchQueueManagerMetrics_FullMethodName = "/cloudidl.queue.InternalQueueManagerService/WatchQueueManagerMetrics"
)

// InternalQueueManagerServiceClient is the client API for InternalQueueManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalQueueManagerServiceClient interface {
	// Stream real-time in-memory queue metrics. The server pushes metrics at a minimum heartbeat interval.
	WatchQueueManagerMetrics(ctx context.Context, in *WatchQueueManagerMetricsRequest, opts ...grpc.CallOption) (InternalQueueManagerService_WatchQueueManagerMetricsClient, error)
}

type internalQueueManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalQueueManagerServiceClient(cc grpc.ClientConnInterface) InternalQueueManagerServiceClient {
	return &internalQueueManagerServiceClient{cc}
}

func (c *internalQueueManagerServiceClient) WatchQueueManagerMetrics(ctx context.Context, in *WatchQueueManagerMetricsRequest, opts ...grpc.CallOption) (InternalQueueManagerService_WatchQueueManagerMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &InternalQueueManagerService_ServiceDesc.Streams[0], InternalQueueManagerService_WatchQueueManagerMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &internalQueueManagerServiceWatchQueueManagerMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InternalQueueManagerService_WatchQueueManagerMetricsClient interface {
	Recv() (*WatchQueueManagerMetricsResponse, error)
	grpc.ClientStream
}

type internalQueueManagerServiceWatchQueueManagerMetricsClient struct {
	grpc.ClientStream
}

func (x *internalQueueManagerServiceWatchQueueManagerMetricsClient) Recv() (*WatchQueueManagerMetricsResponse, error) {
	m := new(WatchQueueManagerMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InternalQueueManagerServiceServer is the server API for InternalQueueManagerService service.
// All implementations should embed UnimplementedInternalQueueManagerServiceServer
// for forward compatibility
type InternalQueueManagerServiceServer interface {
	// Stream real-time in-memory queue metrics. The server pushes metrics at a minimum heartbeat interval.
	WatchQueueManagerMetrics(*WatchQueueManagerMetricsRequest, InternalQueueManagerService_WatchQueueManagerMetricsServer) error
}

// UnimplementedInternalQueueManagerServiceServer should be embedded to have forward compatible implementations.
type UnimplementedInternalQueueManagerServiceServer struct {
}

func (UnimplementedInternalQueueManagerServiceServer) WatchQueueManagerMetrics(*WatchQueueManagerMetricsRequest, InternalQueueManagerService_WatchQueueManagerMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchQueueManagerMetrics not implemented")
}

// UnsafeInternalQueueManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalQueueManagerServiceServer will
// result in compilation errors.
type UnsafeInternalQueueManagerServiceServer interface {
	mustEmbedUnimplementedInternalQueueManagerServiceServer()
}

func RegisterInternalQueueManagerServiceServer(s grpc.ServiceRegistrar, srv InternalQueueManagerServiceServer) {
	s.RegisterService(&InternalQueueManagerService_ServiceDesc, srv)
}

func _InternalQueueManagerService_WatchQueueManagerMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchQueueManagerMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InternalQueueManagerServiceServer).WatchQueueManagerMetrics(m, &internalQueueManagerServiceWatchQueueManagerMetricsServer{stream})
}

type InternalQueueManagerService_WatchQueueManagerMetricsServer interface {
	Send(*WatchQueueManagerMetricsResponse) error
	grpc.ServerStream
}

type internalQueueManagerServiceWatchQueueManagerMetricsServer struct {
	grpc.ServerStream
}

func (x *internalQueueManagerServiceWatchQueueManagerMetricsServer) Send(m *WatchQueueManagerMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// InternalQueueManagerService_ServiceDesc is the grpc.ServiceDesc for InternalQueueManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalQueueManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudidl.queue.InternalQueueManagerService",
	HandlerType: (*InternalQueueManagerServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchQueueManagerMetrics",
			Handler:       _InternalQueueManagerService_WatchQueueManagerMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "queue/internal_queue.proto",
}
