// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: queue/internal_queue.proto

package queue

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdateQueueStateToDrainedRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateQueueStateToDrainedRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueStateToDrainedRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// UpdateQueueStateToDrainedRequestMultiError, or nil if none found.
func (m *UpdateQueueStateToDrainedRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueStateToDrainedRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueStateToDrainedRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueStateToDrainedRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueStateToDrainedRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateQueueStateToDrainedRequestMultiError(errors)
	}

	return nil
}

// UpdateQueueStateToDrainedRequestMultiError is an error wrapping multiple
// validation errors returned by
// UpdateQueueStateToDrainedRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateQueueStateToDrainedRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueStateToDrainedRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueStateToDrainedRequestMultiError) AllErrors() []error { return m }

// UpdateQueueStateToDrainedRequestValidationError is the validation error
// returned by UpdateQueueStateToDrainedRequest.Validate if the designated
// constraints aren't met.
type UpdateQueueStateToDrainedRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueStateToDrainedRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueStateToDrainedRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueStateToDrainedRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueStateToDrainedRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueStateToDrainedRequestValidationError) ErrorName() string {
	return "UpdateQueueStateToDrainedRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueStateToDrainedRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueStateToDrainedRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueStateToDrainedRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueStateToDrainedRequestValidationError{}

// Validate checks the field values on UpdateQueueStateToDrainedResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *UpdateQueueStateToDrainedResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueStateToDrainedResponse
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// UpdateQueueStateToDrainedResponseMultiError, or nil if none found.
func (m *UpdateQueueStateToDrainedResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueStateToDrainedResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UpdateQueueStateToDrainedResponseMultiError(errors)
	}

	return nil
}

// UpdateQueueStateToDrainedResponseMultiError is an error wrapping multiple
// validation errors returned by
// UpdateQueueStateToDrainedResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateQueueStateToDrainedResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueStateToDrainedResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueStateToDrainedResponseMultiError) AllErrors() []error { return m }

// UpdateQueueStateToDrainedResponseValidationError is the validation error
// returned by UpdateQueueStateToDrainedResponse.Validate if the designated
// constraints aren't met.
type UpdateQueueStateToDrainedResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueStateToDrainedResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueStateToDrainedResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueStateToDrainedResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueStateToDrainedResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueStateToDrainedResponseValidationError) ErrorName() string {
	return "UpdateQueueStateToDrainedResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueStateToDrainedResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueStateToDrainedResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueStateToDrainedResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueStateToDrainedResponseValidationError{}

// Validate checks the field values on WatchQueueManagerMetricsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WatchQueueManagerMetricsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WatchQueueManagerMetricsRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// WatchQueueManagerMetricsRequestMultiError, or nil if none found.
func (m *WatchQueueManagerMetricsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WatchQueueManagerMetricsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPoolId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WatchQueueManagerMetricsRequestValidationError{
					field:  "PoolId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WatchQueueManagerMetricsRequestValidationError{
					field:  "PoolId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPoolId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WatchQueueManagerMetricsRequestValidationError{
				field:  "PoolId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WatchQueueManagerMetricsRequestMultiError(errors)
	}

	return nil
}

// WatchQueueManagerMetricsRequestMultiError is an error wrapping multiple
// validation errors returned by WatchQueueManagerMetricsRequest.ValidateAll()
// if the designated constraints aren't met.
type WatchQueueManagerMetricsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WatchQueueManagerMetricsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WatchQueueManagerMetricsRequestMultiError) AllErrors() []error { return m }

// WatchQueueManagerMetricsRequestValidationError is the validation error
// returned by WatchQueueManagerMetricsRequest.Validate if the designated
// constraints aren't met.
type WatchQueueManagerMetricsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchQueueManagerMetricsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchQueueManagerMetricsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchQueueManagerMetricsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchQueueManagerMetricsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchQueueManagerMetricsRequestValidationError) ErrorName() string {
	return "WatchQueueManagerMetricsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e WatchQueueManagerMetricsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchQueueManagerMetricsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchQueueManagerMetricsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchQueueManagerMetricsRequestValidationError{}

// Validate checks the field values on WatchQueueManagerMetricsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *WatchQueueManagerMetricsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WatchQueueManagerMetricsResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// WatchQueueManagerMetricsResponseMultiError, or nil if none found.
func (m *WatchQueueManagerMetricsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *WatchQueueManagerMetricsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMetrics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WatchQueueManagerMetricsResponseValidationError{
						field:  fmt.Sprintf("Metrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WatchQueueManagerMetricsResponseValidationError{
						field:  fmt.Sprintf("Metrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WatchQueueManagerMetricsResponseValidationError{
					field:  fmt.Sprintf("Metrics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WatchQueueManagerMetricsResponseMultiError(errors)
	}

	return nil
}

// WatchQueueManagerMetricsResponseMultiError is an error wrapping multiple
// validation errors returned by
// WatchQueueManagerMetricsResponse.ValidateAll() if the designated
// constraints aren't met.
type WatchQueueManagerMetricsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WatchQueueManagerMetricsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WatchQueueManagerMetricsResponseMultiError) AllErrors() []error { return m }

// WatchQueueManagerMetricsResponseValidationError is the validation error
// returned by WatchQueueManagerMetricsResponse.Validate if the designated
// constraints aren't met.
type WatchQueueManagerMetricsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchQueueManagerMetricsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchQueueManagerMetricsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchQueueManagerMetricsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchQueueManagerMetricsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchQueueManagerMetricsResponseValidationError) ErrorName() string {
	return "WatchQueueManagerMetricsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e WatchQueueManagerMetricsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchQueueManagerMetricsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchQueueManagerMetricsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchQueueManagerMetricsResponseValidationError{}
