// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: queue/queue.proto

package queue

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QueueService_CreateQueue_FullMethodName       = "/cloudidl.queue.QueueService/CreateQueue"
	QueueService_UpdateQueue_FullMethodName       = "/cloudidl.queue.QueueService/UpdateQueue"
	QueueService_GetQueue_FullMethodName          = "/cloudidl.queue.QueueService/GetQueue"
	QueueService_UpdateQueueState_FullMethodName  = "/cloudidl.queue.QueueService/UpdateQueueState"
	QueueService_ListQueues_FullMethodName        = "/cloudidl.queue.QueueService/ListQueues"
	QueueService_WatchQueueMetrics_FullMethodName = "/cloudidl.queue.QueueService/WatchQueueMetrics"
	QueueService_ResolveQueue_FullMethodName      = "/cloudidl.queue.QueueService/ResolveQueue"
)

// QueueServiceClient is the client API for QueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueServiceClient interface {
	// Create or update a queue.
	CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error)
	// Update queue spec fully replaces existing spec.
	// Does not partially update only set fields!
	// Client is expected to get entire spec using GetQueue method, update desired fields and
	// then provide entire spec in UpdateQueue.
	UpdateQueue(ctx context.Context, in *UpdateQueueRequest, opts ...grpc.CallOption) (*UpdateQueueResponse, error)
	// Get a queue by name.
	GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error)
	// Update queue status (drain / activate).
	UpdateQueueState(ctx context.Context, in *UpdateQueueStateRequest, opts ...grpc.CallOption) (*UpdateQueueStateResponse, error)
	// List queues within a scope.
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	// Stream real-time queue metrics.
	// This endpoint proxies metrics from leasor's QueueManager via internal API.
	WatchQueueMetrics(ctx context.Context, in *WatchQueueMetricsRequest, opts ...grpc.CallOption) (QueueService_WatchQueueMetricsClient, error)
	// Return the most narrow-scoped queue for given domain, project and queue name.
	// Today, queue name is unique within an org, but we may lift this requirement
	// and have multiple queues with same name, but different scopes in future.
	ResolveQueue(ctx context.Context, in *ResolveQueueRequest, opts ...grpc.CallOption) (*ResolveQueueResponse, error)
}

type queueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueServiceClient(cc grpc.ClientConnInterface) QueueServiceClient {
	return &queueServiceClient{cc}
}

func (c *queueServiceClient) CreateQueue(ctx context.Context, in *CreateQueueRequest, opts ...grpc.CallOption) (*CreateQueueResponse, error) {
	out := new(CreateQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_CreateQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) UpdateQueue(ctx context.Context, in *UpdateQueueRequest, opts ...grpc.CallOption) (*UpdateQueueResponse, error) {
	out := new(UpdateQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_UpdateQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error) {
	out := new(GetQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_GetQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) UpdateQueueState(ctx context.Context, in *UpdateQueueStateRequest, opts ...grpc.CallOption) (*UpdateQueueStateResponse, error) {
	out := new(UpdateQueueStateResponse)
	err := c.cc.Invoke(ctx, QueueService_UpdateQueueState_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, QueueService_ListQueues_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) WatchQueueMetrics(ctx context.Context, in *WatchQueueMetricsRequest, opts ...grpc.CallOption) (QueueService_WatchQueueMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &QueueService_ServiceDesc.Streams[0], QueueService_WatchQueueMetrics_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &queueServiceWatchQueueMetricsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type QueueService_WatchQueueMetricsClient interface {
	Recv() (*WatchQueueMetricsResponse, error)
	grpc.ClientStream
}

type queueServiceWatchQueueMetricsClient struct {
	grpc.ClientStream
}

func (x *queueServiceWatchQueueMetricsClient) Recv() (*WatchQueueMetricsResponse, error) {
	m := new(WatchQueueMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queueServiceClient) ResolveQueue(ctx context.Context, in *ResolveQueueRequest, opts ...grpc.CallOption) (*ResolveQueueResponse, error) {
	out := new(ResolveQueueResponse)
	err := c.cc.Invoke(ctx, QueueService_ResolveQueue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServiceServer is the server API for QueueService service.
// All implementations should embed UnimplementedQueueServiceServer
// for forward compatibility
type QueueServiceServer interface {
	// Create or update a queue.
	CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error)
	// Update queue spec fully replaces existing spec.
	// Does not partially update only set fields!
	// Client is expected to get entire spec using GetQueue method, update desired fields and
	// then provide entire spec in UpdateQueue.
	UpdateQueue(context.Context, *UpdateQueueRequest) (*UpdateQueueResponse, error)
	// Get a queue by name.
	GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error)
	// Update queue status (drain / activate).
	UpdateQueueState(context.Context, *UpdateQueueStateRequest) (*UpdateQueueStateResponse, error)
	// List queues within a scope.
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	// Stream real-time queue metrics.
	// This endpoint proxies metrics from leasor's QueueManager via internal API.
	WatchQueueMetrics(*WatchQueueMetricsRequest, QueueService_WatchQueueMetricsServer) error
	// Return the most narrow-scoped queue for given domain, project and queue name.
	// Today, queue name is unique within an org, but we may lift this requirement
	// and have multiple queues with same name, but different scopes in future.
	ResolveQueue(context.Context, *ResolveQueueRequest) (*ResolveQueueResponse, error)
}

// UnimplementedQueueServiceServer should be embedded to have forward compatible implementations.
type UnimplementedQueueServiceServer struct {
}

func (UnimplementedQueueServiceServer) CreateQueue(context.Context, *CreateQueueRequest) (*CreateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQueue not implemented")
}
func (UnimplementedQueueServiceServer) UpdateQueue(context.Context, *UpdateQueueRequest) (*UpdateQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQueue not implemented")
}
func (UnimplementedQueueServiceServer) GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedQueueServiceServer) UpdateQueueState(context.Context, *UpdateQueueStateRequest) (*UpdateQueueStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQueueState not implemented")
}
func (UnimplementedQueueServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedQueueServiceServer) WatchQueueMetrics(*WatchQueueMetricsRequest, QueueService_WatchQueueMetricsServer) error {
	return status.Errorf(codes.Unimplemented, "method WatchQueueMetrics not implemented")
}
func (UnimplementedQueueServiceServer) ResolveQueue(context.Context, *ResolveQueueRequest) (*ResolveQueueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveQueue not implemented")
}

// UnsafeQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServiceServer will
// result in compilation errors.
type UnsafeQueueServiceServer interface {
	mustEmbedUnimplementedQueueServiceServer()
}

func RegisterQueueServiceServer(s grpc.ServiceRegistrar, srv QueueServiceServer) {
	s.RegisterService(&QueueService_ServiceDesc, srv)
}

func _QueueService_CreateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).CreateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_CreateQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).CreateQueue(ctx, req.(*CreateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_UpdateQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).UpdateQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_UpdateQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).UpdateQueue(ctx, req.(*UpdateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_GetQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).GetQueue(ctx, req.(*GetQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_UpdateQueueState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQueueStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).UpdateQueueState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_UpdateQueueState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).UpdateQueueState(ctx, req.(*UpdateQueueStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_WatchQueueMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchQueueMetricsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueueServiceServer).WatchQueueMetrics(m, &queueServiceWatchQueueMetricsServer{stream})
}

type QueueService_WatchQueueMetricsServer interface {
	Send(*WatchQueueMetricsResponse) error
	grpc.ServerStream
}

type queueServiceWatchQueueMetricsServer struct {
	grpc.ServerStream
}

func (x *queueServiceWatchQueueMetricsServer) Send(m *WatchQueueMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _QueueService_ResolveQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).ResolveQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_ResolveQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).ResolveQueue(ctx, req.(*ResolveQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueService_ServiceDesc is the grpc.ServiceDesc for QueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudidl.queue.QueueService",
	HandlerType: (*QueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQueue",
			Handler:    _QueueService_CreateQueue_Handler,
		},
		{
			MethodName: "UpdateQueue",
			Handler:    _QueueService_UpdateQueue_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _QueueService_GetQueue_Handler,
		},
		{
			MethodName: "UpdateQueueState",
			Handler:    _QueueService_UpdateQueueState_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _QueueService_ListQueues_Handler,
		},
		{
			MethodName: "ResolveQueue",
			Handler:    _QueueService_ResolveQueue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchQueueMetrics",
			Handler:       _QueueService_WatchQueueMetrics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "queue/queue.proto",
}
