// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: queue/queue.proto

package queue

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on QueueStatus with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueueStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueueStatus with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueueStatusMultiError, or
// nil if none found.
func (m *QueueStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *QueueStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for State

	for idx, item := range m.GetAvailableClusters() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, QueueStatusValidationError{
						field:  fmt.Sprintf("AvailableClusters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, QueueStatusValidationError{
						field:  fmt.Sprintf("AvailableClusters[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return QueueStatusValidationError{
					field:  fmt.Sprintf("AvailableClusters[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return QueueStatusMultiError(errors)
	}

	return nil
}

// QueueStatusMultiError is an error wrapping multiple validation errors
// returned by QueueStatus.ValidateAll() if the designated constraints aren't met.
type QueueStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueueStatusMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueueStatusMultiError) AllErrors() []error { return m }

// QueueStatusValidationError is the validation error returned by
// QueueStatus.Validate if the designated constraints aren't met.
type QueueStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueStatusValidationError) ErrorName() string { return "QueueStatusValidationError" }

// Error satisfies the builtin error interface
func (e QueueStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueueStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueStatusValidationError{}

// Validate checks the field values on Queue with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Queue) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Queue with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in QueueMultiError, or nil if none found.
func (m *Queue) ValidateAll() error {
	return m.validate(true)
}

func (m *Queue) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetStatus()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "Status",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetStatus()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueValidationError{
				field:  "Status",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueueMultiError(errors)
	}

	return nil
}

// QueueMultiError is an error wrapping multiple validation errors returned by
// Queue.ValidateAll() if the designated constraints aren't met.
type QueueMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueueMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueueMultiError) AllErrors() []error { return m }

// QueueValidationError is the validation error returned by Queue.Validate if
// the designated constraints aren't met.
type QueueValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueValidationError) ErrorName() string { return "QueueValidationError" }

// Error satisfies the builtin error interface
func (e QueueValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueue.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueValidationError{}

// Validate checks the field values on QueueSpec with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueueSpec) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueueSpec with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueueSpecMultiError, or nil
// if none found.
func (m *QueueSpec) ValidateAll() error {
	return m.validate(true)
}

func (m *QueueSpec) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunConcurrency

	// no validation rules for ActionConcurrency

	// no validation rules for Depth

	// no validation rules for Priority

	// no validation rules for Fairness

	// no validation rules for ClusterPoolName

	if len(errors) > 0 {
		return QueueSpecMultiError(errors)
	}

	return nil
}

// QueueSpecMultiError is an error wrapping multiple validation errors returned
// by QueueSpec.ValidateAll() if the designated constraints aren't met.
type QueueSpecMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueueSpecMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueueSpecMultiError) AllErrors() []error { return m }

// QueueSpecValidationError is the validation error returned by
// QueueSpec.Validate if the designated constraints aren't met.
type QueueSpecValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueSpecValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueSpecValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueSpecValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueSpecValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueSpecValidationError) ErrorName() string { return "QueueSpecValidationError" }

// Error satisfies the builtin error interface
func (e QueueSpecValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueueSpec.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueSpecValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueSpecValidationError{}

// Validate checks the field values on QueueMetrics with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *QueueMetrics) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on QueueMetrics with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in QueueMetricsMultiError, or
// nil if none found.
func (m *QueueMetrics) ValidateAll() error {
	return m.validate(true)
}

func (m *QueueMetrics) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueMetricsValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueMetricsValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueMetricsValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for RunsInFlight

	// no validation rules for ActionsInFlight

	// no validation rules for CurrentDepth

	if all {
		switch v := interface{}(m.GetObservedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, QueueMetricsValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, QueueMetricsValidationError{
					field:  "ObservedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetObservedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return QueueMetricsValidationError{
				field:  "ObservedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return QueueMetricsMultiError(errors)
	}

	return nil
}

// QueueMetricsMultiError is an error wrapping multiple validation errors
// returned by QueueMetrics.ValidateAll() if the designated constraints aren't met.
type QueueMetricsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m QueueMetricsMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m QueueMetricsMultiError) AllErrors() []error { return m }

// QueueMetricsValidationError is the validation error returned by
// QueueMetrics.Validate if the designated constraints aren't met.
type QueueMetricsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e QueueMetricsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e QueueMetricsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e QueueMetricsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e QueueMetricsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e QueueMetricsValidationError) ErrorName() string { return "QueueMetricsValidationError" }

// Error satisfies the builtin error interface
func (e QueueMetricsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sQueueMetrics.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = QueueMetricsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = QueueMetricsValidationError{}

// Validate checks the field values on CreateQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateQueueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateQueueRequestMultiError, or nil if none found.
func (m *CreateQueueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateQueueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateQueueRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateQueueRequestValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateQueueRequestValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateQueueRequestValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for State

	if len(errors) > 0 {
		return CreateQueueRequestMultiError(errors)
	}

	return nil
}

// CreateQueueRequestMultiError is an error wrapping multiple validation errors
// returned by CreateQueueRequest.ValidateAll() if the designated constraints
// aren't met.
type CreateQueueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateQueueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateQueueRequestMultiError) AllErrors() []error { return m }

// CreateQueueRequestValidationError is the validation error returned by
// CreateQueueRequest.Validate if the designated constraints aren't met.
type CreateQueueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateQueueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateQueueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateQueueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateQueueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateQueueRequestValidationError) ErrorName() string {
	return "CreateQueueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateQueueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateQueueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateQueueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateQueueRequestValidationError{}

// Validate checks the field values on CreateQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateQueueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateQueueResponseMultiError, or nil if none found.
func (m *CreateQueueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateQueueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQueue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateQueueResponseValidationError{
				field:  "Queue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateQueueResponseMultiError(errors)
	}

	return nil
}

// CreateQueueResponseMultiError is an error wrapping multiple validation
// errors returned by CreateQueueResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateQueueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateQueueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateQueueResponseMultiError) AllErrors() []error { return m }

// CreateQueueResponseValidationError is the validation error returned by
// CreateQueueResponse.Validate if the designated constraints aren't met.
type CreateQueueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateQueueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateQueueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateQueueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateQueueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateQueueResponseValidationError) ErrorName() string {
	return "CreateQueueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateQueueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateQueueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateQueueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateQueueResponseValidationError{}

// Validate checks the field values on UpdateQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateQueueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateQueueRequestMultiError, or nil if none found.
func (m *UpdateQueueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetSpec()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueRequestValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueRequestValidationError{
					field:  "Spec",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetSpec()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueRequestValidationError{
				field:  "Spec",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateQueueRequestMultiError(errors)
	}

	return nil
}

// UpdateQueueRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateQueueRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateQueueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueRequestMultiError) AllErrors() []error { return m }

// UpdateQueueRequestValidationError is the validation error returned by
// UpdateQueueRequest.Validate if the designated constraints aren't met.
type UpdateQueueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueRequestValidationError) ErrorName() string {
	return "UpdateQueueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueRequestValidationError{}

// Validate checks the field values on UpdateQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateQueueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateQueueResponseMultiError, or nil if none found.
func (m *UpdateQueueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQueue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueResponseValidationError{
				field:  "Queue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateQueueResponseMultiError(errors)
	}

	return nil
}

// UpdateQueueResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateQueueResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateQueueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueResponseMultiError) AllErrors() []error { return m }

// UpdateQueueResponseValidationError is the validation error returned by
// UpdateQueueResponse.Validate if the designated constraints aren't met.
type UpdateQueueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueResponseValidationError) ErrorName() string {
	return "UpdateQueueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueResponseValidationError{}

// Validate checks the field values on GetQueueRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetQueueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetQueueRequestMultiError, or nil if none found.
func (m *GetQueueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetQueueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetQueueRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetQueueRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetQueueRequestMultiError(errors)
	}

	return nil
}

// GetQueueRequestMultiError is an error wrapping multiple validation errors
// returned by GetQueueRequest.ValidateAll() if the designated constraints
// aren't met.
type GetQueueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetQueueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetQueueRequestMultiError) AllErrors() []error { return m }

// GetQueueRequestValidationError is the validation error returned by
// GetQueueRequest.Validate if the designated constraints aren't met.
type GetQueueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetQueueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetQueueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetQueueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetQueueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetQueueRequestValidationError) ErrorName() string { return "GetQueueRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetQueueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetQueueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetQueueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetQueueRequestValidationError{}

// Validate checks the field values on GetQueueResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetQueueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetQueueResponseMultiError, or nil if none found.
func (m *GetQueueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetQueueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQueue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetQueueResponseValidationError{
				field:  "Queue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetQueueResponseMultiError(errors)
	}

	return nil
}

// GetQueueResponseMultiError is an error wrapping multiple validation errors
// returned by GetQueueResponse.ValidateAll() if the designated constraints
// aren't met.
type GetQueueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetQueueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetQueueResponseMultiError) AllErrors() []error { return m }

// GetQueueResponseValidationError is the validation error returned by
// GetQueueResponse.Validate if the designated constraints aren't met.
type GetQueueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetQueueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetQueueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetQueueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetQueueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetQueueResponseValidationError) ErrorName() string { return "GetQueueResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetQueueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetQueueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetQueueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetQueueResponseValidationError{}

// Validate checks the field values on UpdateQueueStateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateQueueStateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueStateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateQueueStateRequestMultiError, or nil if none found.
func (m *UpdateQueueStateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueStateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueStateRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueStateRequestValidationError{
					field:  "Id",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueStateRequestValidationError{
				field:  "Id",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for State

	if len(errors) > 0 {
		return UpdateQueueStateRequestMultiError(errors)
	}

	return nil
}

// UpdateQueueStateRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateQueueStateRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateQueueStateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueStateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueStateRequestMultiError) AllErrors() []error { return m }

// UpdateQueueStateRequestValidationError is the validation error returned by
// UpdateQueueStateRequest.Validate if the designated constraints aren't met.
type UpdateQueueStateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueStateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueStateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueStateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueStateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueStateRequestValidationError) ErrorName() string {
	return "UpdateQueueStateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueStateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueStateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueStateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueStateRequestValidationError{}

// Validate checks the field values on UpdateQueueStateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateQueueStateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateQueueStateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateQueueStateResponseMultiError, or nil if none found.
func (m *UpdateQueueStateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateQueueStateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQueue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateQueueStateResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateQueueStateResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateQueueStateResponseValidationError{
				field:  "Queue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateQueueStateResponseMultiError(errors)
	}

	return nil
}

// UpdateQueueStateResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateQueueStateResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateQueueStateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateQueueStateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateQueueStateResponseMultiError) AllErrors() []error { return m }

// UpdateQueueStateResponseValidationError is the validation error returned by
// UpdateQueueStateResponse.Validate if the designated constraints aren't met.
type UpdateQueueStateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateQueueStateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateQueueStateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateQueueStateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateQueueStateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateQueueStateResponseValidationError) ErrorName() string {
	return "UpdateQueueStateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateQueueStateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateQueueStateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateQueueStateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateQueueStateResponseValidationError{}

// Validate checks the field values on ListQueuesRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListQueuesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQueuesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListQueuesRequestMultiError, or nil if none found.
func (m *ListQueuesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQueuesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Organization

	if all {
		switch v := interface{}(m.GetRequest()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListQueuesRequestValidationError{
					field:  "Request",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListQueuesRequestValidationError{
					field:  "Request",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRequest()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListQueuesRequestValidationError{
				field:  "Request",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListQueuesRequestMultiError(errors)
	}

	return nil
}

// ListQueuesRequestMultiError is an error wrapping multiple validation errors
// returned by ListQueuesRequest.ValidateAll() if the designated constraints
// aren't met.
type ListQueuesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQueuesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQueuesRequestMultiError) AllErrors() []error { return m }

// ListQueuesRequestValidationError is the validation error returned by
// ListQueuesRequest.Validate if the designated constraints aren't met.
type ListQueuesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQueuesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQueuesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQueuesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQueuesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQueuesRequestValidationError) ErrorName() string {
	return "ListQueuesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListQueuesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQueuesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQueuesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQueuesRequestValidationError{}

// Validate checks the field values on ListQueuesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListQueuesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListQueuesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListQueuesResponseMultiError, or nil if none found.
func (m *ListQueuesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListQueuesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetQueues() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListQueuesResponseValidationError{
						field:  fmt.Sprintf("Queues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListQueuesResponseValidationError{
						field:  fmt.Sprintf("Queues[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListQueuesResponseValidationError{
					field:  fmt.Sprintf("Queues[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Token

	if len(errors) > 0 {
		return ListQueuesResponseMultiError(errors)
	}

	return nil
}

// ListQueuesResponseMultiError is an error wrapping multiple validation errors
// returned by ListQueuesResponse.ValidateAll() if the designated constraints
// aren't met.
type ListQueuesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListQueuesResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListQueuesResponseMultiError) AllErrors() []error { return m }

// ListQueuesResponseValidationError is the validation error returned by
// ListQueuesResponse.Validate if the designated constraints aren't met.
type ListQueuesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListQueuesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListQueuesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListQueuesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListQueuesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListQueuesResponseValidationError) ErrorName() string {
	return "ListQueuesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListQueuesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListQueuesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListQueuesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListQueuesResponseValidationError{}

// Validate checks the field values on WatchQueueMetricsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WatchQueueMetricsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WatchQueueMetricsRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WatchQueueMetricsRequestMultiError, or nil if none found.
func (m *WatchQueueMetricsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *WatchQueueMetricsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPoolId()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, WatchQueueMetricsRequestValidationError{
					field:  "PoolId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, WatchQueueMetricsRequestValidationError{
					field:  "PoolId",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPoolId()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WatchQueueMetricsRequestValidationError{
				field:  "PoolId",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return WatchQueueMetricsRequestMultiError(errors)
	}

	return nil
}

// WatchQueueMetricsRequestMultiError is an error wrapping multiple validation
// errors returned by WatchQueueMetricsRequest.ValidateAll() if the designated
// constraints aren't met.
type WatchQueueMetricsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WatchQueueMetricsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WatchQueueMetricsRequestMultiError) AllErrors() []error { return m }

// WatchQueueMetricsRequestValidationError is the validation error returned by
// WatchQueueMetricsRequest.Validate if the designated constraints aren't met.
type WatchQueueMetricsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchQueueMetricsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchQueueMetricsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchQueueMetricsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchQueueMetricsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchQueueMetricsRequestValidationError) ErrorName() string {
	return "WatchQueueMetricsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e WatchQueueMetricsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchQueueMetricsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchQueueMetricsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchQueueMetricsRequestValidationError{}

// Validate checks the field values on WatchQueueMetricsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *WatchQueueMetricsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on WatchQueueMetricsResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// WatchQueueMetricsResponseMultiError, or nil if none found.
func (m *WatchQueueMetricsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *WatchQueueMetricsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetMetrics() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, WatchQueueMetricsResponseValidationError{
						field:  fmt.Sprintf("Metrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, WatchQueueMetricsResponseValidationError{
						field:  fmt.Sprintf("Metrics[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return WatchQueueMetricsResponseValidationError{
					field:  fmt.Sprintf("Metrics[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return WatchQueueMetricsResponseMultiError(errors)
	}

	return nil
}

// WatchQueueMetricsResponseMultiError is an error wrapping multiple validation
// errors returned by WatchQueueMetricsResponse.ValidateAll() if the
// designated constraints aren't met.
type WatchQueueMetricsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m WatchQueueMetricsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m WatchQueueMetricsResponseMultiError) AllErrors() []error { return m }

// WatchQueueMetricsResponseValidationError is the validation error returned by
// WatchQueueMetricsResponse.Validate if the designated constraints aren't met.
type WatchQueueMetricsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WatchQueueMetricsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WatchQueueMetricsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WatchQueueMetricsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WatchQueueMetricsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WatchQueueMetricsResponseValidationError) ErrorName() string {
	return "WatchQueueMetricsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e WatchQueueMetricsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWatchQueueMetricsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WatchQueueMetricsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WatchQueueMetricsResponseValidationError{}

// Validate checks the field values on ResolveQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResolveQueueRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResolveQueueRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResolveQueueRequestMultiError, or nil if none found.
func (m *ResolveQueueRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ResolveQueueRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for QueueName

	switch v := m.QueueScope.(type) {
	case *ResolveQueueRequest_RunId:
		if v == nil {
			err := ResolveQueueRequestValidationError{
				field:  "QueueScope",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRunId()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResolveQueueRequestValidationError{
						field:  "RunId",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResolveQueueRequestValidationError{
						field:  "RunId",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRunId()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResolveQueueRequestValidationError{
					field:  "RunId",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *ResolveQueueRequest_SettingKey:
		if v == nil {
			err := ResolveQueueRequestValidationError{
				field:  "QueueScope",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetSettingKey()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ResolveQueueRequestValidationError{
						field:  "SettingKey",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ResolveQueueRequestValidationError{
						field:  "SettingKey",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetSettingKey()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ResolveQueueRequestValidationError{
					field:  "SettingKey",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return ResolveQueueRequestMultiError(errors)
	}

	return nil
}

// ResolveQueueRequestMultiError is an error wrapping multiple validation
// errors returned by ResolveQueueRequest.ValidateAll() if the designated
// constraints aren't met.
type ResolveQueueRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResolveQueueRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResolveQueueRequestMultiError) AllErrors() []error { return m }

// ResolveQueueRequestValidationError is the validation error returned by
// ResolveQueueRequest.Validate if the designated constraints aren't met.
type ResolveQueueRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResolveQueueRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResolveQueueRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResolveQueueRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResolveQueueRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResolveQueueRequestValidationError) ErrorName() string {
	return "ResolveQueueRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ResolveQueueRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResolveQueueRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResolveQueueRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResolveQueueRequestValidationError{}

// Validate checks the field values on ResolveQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ResolveQueueResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ResolveQueueResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ResolveQueueResponseMultiError, or nil if none found.
func (m *ResolveQueueResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ResolveQueueResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetQueue()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ResolveQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ResolveQueueResponseValidationError{
					field:  "Queue",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetQueue()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ResolveQueueResponseValidationError{
				field:  "Queue",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ResolveQueueResponseMultiError(errors)
	}

	return nil
}

// ResolveQueueResponseMultiError is an error wrapping multiple validation
// errors returned by ResolveQueueResponse.ValidateAll() if the designated
// constraints aren't met.
type ResolveQueueResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ResolveQueueResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ResolveQueueResponseMultiError) AllErrors() []error { return m }

// ResolveQueueResponseValidationError is the validation error returned by
// ResolveQueueResponse.Validate if the designated constraints aren't met.
type ResolveQueueResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ResolveQueueResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ResolveQueueResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ResolveQueueResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ResolveQueueResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ResolveQueueResponseValidationError) ErrorName() string {
	return "ResolveQueueResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ResolveQueueResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sResolveQueueResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ResolveQueueResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ResolveQueueResponseValidationError{}
