// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: queue/internal_queue.proto

package queueconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	queue "github.com/unionai/cloud/gen/pb-go/queue"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InternalQueueServiceName is the fully-qualified name of the InternalQueueService service.
	InternalQueueServiceName = "cloudidl.queue.InternalQueueService"
	// InternalQueueManagerServiceName is the fully-qualified name of the InternalQueueManagerService
	// service.
	InternalQueueManagerServiceName = "cloudidl.queue.InternalQueueManagerService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InternalQueueServiceUpdateQueueStateToDrainedProcedure is the fully-qualified name of the
	// InternalQueueService's UpdateQueueStateToDrained RPC.
	InternalQueueServiceUpdateQueueStateToDrainedProcedure = "/cloudidl.queue.InternalQueueService/UpdateQueueStateToDrained"
	// InternalQueueManagerServiceWatchQueueManagerMetricsProcedure is the fully-qualified name of the
	// InternalQueueManagerService's WatchQueueManagerMetrics RPC.
	InternalQueueManagerServiceWatchQueueManagerMetricsProcedure = "/cloudidl.queue.InternalQueueManagerService/WatchQueueManagerMetrics"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	internalQueueServiceServiceDescriptor                               = queue.File_queue_internal_queue_proto.Services().ByName("InternalQueueService")
	internalQueueServiceUpdateQueueStateToDrainedMethodDescriptor       = internalQueueServiceServiceDescriptor.Methods().ByName("UpdateQueueStateToDrained")
	internalQueueManagerServiceServiceDescriptor                        = queue.File_queue_internal_queue_proto.Services().ByName("InternalQueueManagerService")
	internalQueueManagerServiceWatchQueueManagerMetricsMethodDescriptor = internalQueueManagerServiceServiceDescriptor.Methods().ByName("WatchQueueManagerMetrics")
)

// InternalQueueServiceClient is a client for the cloudidl.queue.InternalQueueService service.
type InternalQueueServiceClient interface {
	// When queue is drained in leasor service, it should call this endpoint to update queue state to DRAINED.
	UpdateQueueStateToDrained(context.Context, *connect.Request[queue.UpdateQueueStateToDrainedRequest]) (*connect.Response[queue.UpdateQueueStateToDrainedResponse], error)
}

// NewInternalQueueServiceClient constructs a client for the cloudidl.queue.InternalQueueService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInternalQueueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InternalQueueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &internalQueueServiceClient{
		updateQueueStateToDrained: connect.NewClient[queue.UpdateQueueStateToDrainedRequest, queue.UpdateQueueStateToDrainedResponse](
			httpClient,
			baseURL+InternalQueueServiceUpdateQueueStateToDrainedProcedure,
			connect.WithSchema(internalQueueServiceUpdateQueueStateToDrainedMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// internalQueueServiceClient implements InternalQueueServiceClient.
type internalQueueServiceClient struct {
	updateQueueStateToDrained *connect.Client[queue.UpdateQueueStateToDrainedRequest, queue.UpdateQueueStateToDrainedResponse]
}

// UpdateQueueStateToDrained calls cloudidl.queue.InternalQueueService.UpdateQueueStateToDrained.
func (c *internalQueueServiceClient) UpdateQueueStateToDrained(ctx context.Context, req *connect.Request[queue.UpdateQueueStateToDrainedRequest]) (*connect.Response[queue.UpdateQueueStateToDrainedResponse], error) {
	return c.updateQueueStateToDrained.CallUnary(ctx, req)
}

// InternalQueueServiceHandler is an implementation of the cloudidl.queue.InternalQueueService
// service.
type InternalQueueServiceHandler interface {
	// When queue is drained in leasor service, it should call this endpoint to update queue state to DRAINED.
	UpdateQueueStateToDrained(context.Context, *connect.Request[queue.UpdateQueueStateToDrainedRequest]) (*connect.Response[queue.UpdateQueueStateToDrainedResponse], error)
}

// NewInternalQueueServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInternalQueueServiceHandler(svc InternalQueueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	internalQueueServiceUpdateQueueStateToDrainedHandler := connect.NewUnaryHandler(
		InternalQueueServiceUpdateQueueStateToDrainedProcedure,
		svc.UpdateQueueStateToDrained,
		connect.WithSchema(internalQueueServiceUpdateQueueStateToDrainedMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.queue.InternalQueueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InternalQueueServiceUpdateQueueStateToDrainedProcedure:
			internalQueueServiceUpdateQueueStateToDrainedHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInternalQueueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInternalQueueServiceHandler struct{}

func (UnimplementedInternalQueueServiceHandler) UpdateQueueStateToDrained(context.Context, *connect.Request[queue.UpdateQueueStateToDrainedRequest]) (*connect.Response[queue.UpdateQueueStateToDrainedResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.InternalQueueService.UpdateQueueStateToDrained is not implemented"))
}

// InternalQueueManagerServiceClient is a client for the cloudidl.queue.InternalQueueManagerService
// service.
type InternalQueueManagerServiceClient interface {
	// Stream real-time in-memory queue metrics. The server pushes metrics at a minimum heartbeat interval.
	WatchQueueManagerMetrics(context.Context, *connect.Request[queue.WatchQueueManagerMetricsRequest]) (*connect.ServerStreamForClient[queue.WatchQueueManagerMetricsResponse], error)
}

// NewInternalQueueManagerServiceClient constructs a client for the
// cloudidl.queue.InternalQueueManagerService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInternalQueueManagerServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InternalQueueManagerServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &internalQueueManagerServiceClient{
		watchQueueManagerMetrics: connect.NewClient[queue.WatchQueueManagerMetricsRequest, queue.WatchQueueManagerMetricsResponse](
			httpClient,
			baseURL+InternalQueueManagerServiceWatchQueueManagerMetricsProcedure,
			connect.WithSchema(internalQueueManagerServiceWatchQueueManagerMetricsMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// internalQueueManagerServiceClient implements InternalQueueManagerServiceClient.
type internalQueueManagerServiceClient struct {
	watchQueueManagerMetrics *connect.Client[queue.WatchQueueManagerMetricsRequest, queue.WatchQueueManagerMetricsResponse]
}

// WatchQueueManagerMetrics calls
// cloudidl.queue.InternalQueueManagerService.WatchQueueManagerMetrics.
func (c *internalQueueManagerServiceClient) WatchQueueManagerMetrics(ctx context.Context, req *connect.Request[queue.WatchQueueManagerMetricsRequest]) (*connect.ServerStreamForClient[queue.WatchQueueManagerMetricsResponse], error) {
	return c.watchQueueManagerMetrics.CallServerStream(ctx, req)
}

// InternalQueueManagerServiceHandler is an implementation of the
// cloudidl.queue.InternalQueueManagerService service.
type InternalQueueManagerServiceHandler interface {
	// Stream real-time in-memory queue metrics. The server pushes metrics at a minimum heartbeat interval.
	WatchQueueManagerMetrics(context.Context, *connect.Request[queue.WatchQueueManagerMetricsRequest], *connect.ServerStream[queue.WatchQueueManagerMetricsResponse]) error
}

// NewInternalQueueManagerServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInternalQueueManagerServiceHandler(svc InternalQueueManagerServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	internalQueueManagerServiceWatchQueueManagerMetricsHandler := connect.NewServerStreamHandler(
		InternalQueueManagerServiceWatchQueueManagerMetricsProcedure,
		svc.WatchQueueManagerMetrics,
		connect.WithSchema(internalQueueManagerServiceWatchQueueManagerMetricsMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.queue.InternalQueueManagerService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InternalQueueManagerServiceWatchQueueManagerMetricsProcedure:
			internalQueueManagerServiceWatchQueueManagerMetricsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInternalQueueManagerServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInternalQueueManagerServiceHandler struct{}

func (UnimplementedInternalQueueManagerServiceHandler) WatchQueueManagerMetrics(context.Context, *connect.Request[queue.WatchQueueManagerMetricsRequest], *connect.ServerStream[queue.WatchQueueManagerMetricsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.InternalQueueManagerService.WatchQueueManagerMetrics is not implemented"))
}
