// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: queue/queue.proto

package queueconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	queue "github.com/unionai/cloud/gen/pb-go/queue"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// QueueServiceName is the fully-qualified name of the QueueService service.
	QueueServiceName = "cloudidl.queue.QueueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// QueueServiceCreateQueueProcedure is the fully-qualified name of the QueueService's CreateQueue
	// RPC.
	QueueServiceCreateQueueProcedure = "/cloudidl.queue.QueueService/CreateQueue"
	// QueueServiceUpdateQueueProcedure is the fully-qualified name of the QueueService's UpdateQueue
	// RPC.
	QueueServiceUpdateQueueProcedure = "/cloudidl.queue.QueueService/UpdateQueue"
	// QueueServiceGetQueueProcedure is the fully-qualified name of the QueueService's GetQueue RPC.
	QueueServiceGetQueueProcedure = "/cloudidl.queue.QueueService/GetQueue"
	// QueueServiceUpdateQueueStateProcedure is the fully-qualified name of the QueueService's
	// UpdateQueueState RPC.
	QueueServiceUpdateQueueStateProcedure = "/cloudidl.queue.QueueService/UpdateQueueState"
	// QueueServiceListQueuesProcedure is the fully-qualified name of the QueueService's ListQueues RPC.
	QueueServiceListQueuesProcedure = "/cloudidl.queue.QueueService/ListQueues"
	// QueueServiceWatchQueueMetricsProcedure is the fully-qualified name of the QueueService's
	// WatchQueueMetrics RPC.
	QueueServiceWatchQueueMetricsProcedure = "/cloudidl.queue.QueueService/WatchQueueMetrics"
	// QueueServiceDeleteQueueProcedure is the fully-qualified name of the QueueService's DeleteQueue
	// RPC.
	QueueServiceDeleteQueueProcedure = "/cloudidl.queue.QueueService/DeleteQueue"
	// QueueServiceUndeleteQueueProcedure is the fully-qualified name of the QueueService's
	// UndeleteQueue RPC.
	QueueServiceUndeleteQueueProcedure = "/cloudidl.queue.QueueService/UndeleteQueue"
	// QueueServiceResolveQueueProcedure is the fully-qualified name of the QueueService's ResolveQueue
	// RPC.
	QueueServiceResolveQueueProcedure = "/cloudidl.queue.QueueService/ResolveQueue"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	queueServiceServiceDescriptor                 = queue.File_queue_queue_proto.Services().ByName("QueueService")
	queueServiceCreateQueueMethodDescriptor       = queueServiceServiceDescriptor.Methods().ByName("CreateQueue")
	queueServiceUpdateQueueMethodDescriptor       = queueServiceServiceDescriptor.Methods().ByName("UpdateQueue")
	queueServiceGetQueueMethodDescriptor          = queueServiceServiceDescriptor.Methods().ByName("GetQueue")
	queueServiceUpdateQueueStateMethodDescriptor  = queueServiceServiceDescriptor.Methods().ByName("UpdateQueueState")
	queueServiceListQueuesMethodDescriptor        = queueServiceServiceDescriptor.Methods().ByName("ListQueues")
	queueServiceWatchQueueMetricsMethodDescriptor = queueServiceServiceDescriptor.Methods().ByName("WatchQueueMetrics")
	queueServiceDeleteQueueMethodDescriptor       = queueServiceServiceDescriptor.Methods().ByName("DeleteQueue")
	queueServiceUndeleteQueueMethodDescriptor     = queueServiceServiceDescriptor.Methods().ByName("UndeleteQueue")
	queueServiceResolveQueueMethodDescriptor      = queueServiceServiceDescriptor.Methods().ByName("ResolveQueue")
)

// QueueServiceClient is a client for the cloudidl.queue.QueueService service.
type QueueServiceClient interface {
	// Create or update a queue.
	// A queue cannot take the name of an existing cluster: that name belongs to the cluster's
	// own implicit queue (see ClusterService.CreateCluster).
	CreateQueue(context.Context, *connect.Request[queue.CreateQueueRequest]) (*connect.Response[queue.CreateQueueResponse], error)
	// Update queue spec fully replaces existing spec.
	// A cluster's co-named implicit queue is the exception: its clusters and cluster pool are
	// managed by that cluster and any request changing either is rejected. Its other fields
	// (concurrency, depth, priority, fairness) stay editable.
	// Does not partially update only set fields!
	// Client is expected to get entire spec using GetQueue method, update desired fields and
	// then provide entire spec in UpdateQueue.
	UpdateQueue(context.Context, *connect.Request[queue.UpdateQueueRequest]) (*connect.Response[queue.UpdateQueueResponse], error)
	// Get a queue by name.
	// Soft-deleted queues are returned too, carrying Queue.deleted_at, so a deleted
	// queue's details stay reachable (e.g. from a run that once targeted it).
	GetQueue(context.Context, *connect.Request[queue.GetQueueRequest]) (*connect.Response[queue.GetQueueResponse], error)
	// Update queue status (drain / activate).
	UpdateQueueState(context.Context, *connect.Request[queue.UpdateQueueStateRequest]) (*connect.Response[queue.UpdateQueueStateResponse], error)
	// List queues within a scope.
	// Soft-deleted queues are excluded unless the request filters on the deleted_at field:
	// function EXISTS lists only soft-deleted queues (the only queues that carry
	// Queue.deleted_at), function NOT_EXISTS is the default of live queues only.
	// This is how a client discovers a deleted queue to pass to UndeleteQueue.
	ListQueues(context.Context, *connect.Request[queue.ListQueuesRequest]) (*connect.Response[queue.ListQueuesResponse], error)
	// Stream real-time queue metrics.
	// This endpoint proxies metrics from leasor's QueueManager via internal API.
	WatchQueueMetrics(context.Context, *connect.Request[queue.WatchQueueMetricsRequest]) (*connect.ServerStreamForClient[queue.WatchQueueMetricsResponse], error)
	// Soft-delete a queue: the record is kept but marked as deleted, so the queue
	// disappears from ResolveQueue (unless include_deleted is set) and from ListQueues.
	// ListQueues can explicitly ask for deleted queues, and GetQueue keeps returning the
	// queue with deleted_at set. A deleted queue is no longer scheduled on.
	// The queue must be in DRAINED state, otherwise the request is rejected: drain it
	// with UpdateQueueState first.
	// A soft-deleted queue keeps its name reserved: CreateQueue with the same name is
	// rejected as already existing until the queue is undeleted.
	// Deleting an already deleted queue is rejected.
	// A queue that is referenced as run.default_queue in settings at any scope cannot be
	// deleted until those settings are updated or unset.
	// The reserved "default" queue is no exception: it can be drained and deleted like any
	// other queue — deleting it is how the reserved "default" pool is emptied of live queues
	// so that the pool itself can be deleted (see ClusterPoolService.Delete). While it is
	// deleted, runs that would fall back to it (no queue named and no run.default_queue
	// setting) are rejected at creation. Nothing re-creates it implicitly; UndeleteQueue
	// brings it back.
	// A cluster's co-named implicit queue may be deleted while its cluster is still live, and
	// is also deleted automatically when the cluster is (see ClusterService.DeleteCluster).
	DeleteQueue(context.Context, *connect.Request[queue.DeleteQueueRequest]) (*connect.Response[queue.DeleteQueueResponse], error)
	// Undelete removes the deletion mark from a soft-deleted queue, effectively re-creating
	// it with the spec it had when it was deleted. The queue comes back in DRAINED state and
	// has to be activated with UpdateQueueState to accept work again.
	// Every cluster the queue routes to must be live and in the queue's cluster pool, and the
	// pool itself must be live — a restored queue must never point at something that is gone.
	// For a cluster's co-named queue that means the cluster has to be undeleted instead, which
	// brings the queue back with it (see ClusterService.UndeleteCluster).
	// Undeleting a queue that is not deleted is rejected.
	UndeleteQueue(context.Context, *connect.Request[queue.UndeleteQueueRequest]) (*connect.Response[queue.UndeleteQueueResponse], error)
	// Return the most narrow-scoped queue for given domain, project and queue name.
	// Today, queue name is unique within an org, but we may lift this requirement
	// and have multiple queues with same name, but different scopes in future.
	// Soft-deleted queues resolve to NotFound unless include_deleted is set.
	ResolveQueue(context.Context, *connect.Request[queue.ResolveQueueRequest]) (*connect.Response[queue.ResolveQueueResponse], error)
}

// NewQueueServiceClient constructs a client for the cloudidl.queue.QueueService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewQueueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) QueueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &queueServiceClient{
		createQueue: connect.NewClient[queue.CreateQueueRequest, queue.CreateQueueResponse](
			httpClient,
			baseURL+QueueServiceCreateQueueProcedure,
			connect.WithSchema(queueServiceCreateQueueMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		updateQueue: connect.NewClient[queue.UpdateQueueRequest, queue.UpdateQueueResponse](
			httpClient,
			baseURL+QueueServiceUpdateQueueProcedure,
			connect.WithSchema(queueServiceUpdateQueueMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getQueue: connect.NewClient[queue.GetQueueRequest, queue.GetQueueResponse](
			httpClient,
			baseURL+QueueServiceGetQueueProcedure,
			connect.WithSchema(queueServiceGetQueueMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		updateQueueState: connect.NewClient[queue.UpdateQueueStateRequest, queue.UpdateQueueStateResponse](
			httpClient,
			baseURL+QueueServiceUpdateQueueStateProcedure,
			connect.WithSchema(queueServiceUpdateQueueStateMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listQueues: connect.NewClient[queue.ListQueuesRequest, queue.ListQueuesResponse](
			httpClient,
			baseURL+QueueServiceListQueuesProcedure,
			connect.WithSchema(queueServiceListQueuesMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		watchQueueMetrics: connect.NewClient[queue.WatchQueueMetricsRequest, queue.WatchQueueMetricsResponse](
			httpClient,
			baseURL+QueueServiceWatchQueueMetricsProcedure,
			connect.WithSchema(queueServiceWatchQueueMetricsMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		deleteQueue: connect.NewClient[queue.DeleteQueueRequest, queue.DeleteQueueResponse](
			httpClient,
			baseURL+QueueServiceDeleteQueueProcedure,
			connect.WithSchema(queueServiceDeleteQueueMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		undeleteQueue: connect.NewClient[queue.UndeleteQueueRequest, queue.UndeleteQueueResponse](
			httpClient,
			baseURL+QueueServiceUndeleteQueueProcedure,
			connect.WithSchema(queueServiceUndeleteQueueMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		resolveQueue: connect.NewClient[queue.ResolveQueueRequest, queue.ResolveQueueResponse](
			httpClient,
			baseURL+QueueServiceResolveQueueProcedure,
			connect.WithSchema(queueServiceResolveQueueMethodDescriptor),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// queueServiceClient implements QueueServiceClient.
type queueServiceClient struct {
	createQueue       *connect.Client[queue.CreateQueueRequest, queue.CreateQueueResponse]
	updateQueue       *connect.Client[queue.UpdateQueueRequest, queue.UpdateQueueResponse]
	getQueue          *connect.Client[queue.GetQueueRequest, queue.GetQueueResponse]
	updateQueueState  *connect.Client[queue.UpdateQueueStateRequest, queue.UpdateQueueStateResponse]
	listQueues        *connect.Client[queue.ListQueuesRequest, queue.ListQueuesResponse]
	watchQueueMetrics *connect.Client[queue.WatchQueueMetricsRequest, queue.WatchQueueMetricsResponse]
	deleteQueue       *connect.Client[queue.DeleteQueueRequest, queue.DeleteQueueResponse]
	undeleteQueue     *connect.Client[queue.UndeleteQueueRequest, queue.UndeleteQueueResponse]
	resolveQueue      *connect.Client[queue.ResolveQueueRequest, queue.ResolveQueueResponse]
}

// CreateQueue calls cloudidl.queue.QueueService.CreateQueue.
func (c *queueServiceClient) CreateQueue(ctx context.Context, req *connect.Request[queue.CreateQueueRequest]) (*connect.Response[queue.CreateQueueResponse], error) {
	return c.createQueue.CallUnary(ctx, req)
}

// UpdateQueue calls cloudidl.queue.QueueService.UpdateQueue.
func (c *queueServiceClient) UpdateQueue(ctx context.Context, req *connect.Request[queue.UpdateQueueRequest]) (*connect.Response[queue.UpdateQueueResponse], error) {
	return c.updateQueue.CallUnary(ctx, req)
}

// GetQueue calls cloudidl.queue.QueueService.GetQueue.
func (c *queueServiceClient) GetQueue(ctx context.Context, req *connect.Request[queue.GetQueueRequest]) (*connect.Response[queue.GetQueueResponse], error) {
	return c.getQueue.CallUnary(ctx, req)
}

// UpdateQueueState calls cloudidl.queue.QueueService.UpdateQueueState.
func (c *queueServiceClient) UpdateQueueState(ctx context.Context, req *connect.Request[queue.UpdateQueueStateRequest]) (*connect.Response[queue.UpdateQueueStateResponse], error) {
	return c.updateQueueState.CallUnary(ctx, req)
}

// ListQueues calls cloudidl.queue.QueueService.ListQueues.
func (c *queueServiceClient) ListQueues(ctx context.Context, req *connect.Request[queue.ListQueuesRequest]) (*connect.Response[queue.ListQueuesResponse], error) {
	return c.listQueues.CallUnary(ctx, req)
}

// WatchQueueMetrics calls cloudidl.queue.QueueService.WatchQueueMetrics.
func (c *queueServiceClient) WatchQueueMetrics(ctx context.Context, req *connect.Request[queue.WatchQueueMetricsRequest]) (*connect.ServerStreamForClient[queue.WatchQueueMetricsResponse], error) {
	return c.watchQueueMetrics.CallServerStream(ctx, req)
}

// DeleteQueue calls cloudidl.queue.QueueService.DeleteQueue.
func (c *queueServiceClient) DeleteQueue(ctx context.Context, req *connect.Request[queue.DeleteQueueRequest]) (*connect.Response[queue.DeleteQueueResponse], error) {
	return c.deleteQueue.CallUnary(ctx, req)
}

// UndeleteQueue calls cloudidl.queue.QueueService.UndeleteQueue.
func (c *queueServiceClient) UndeleteQueue(ctx context.Context, req *connect.Request[queue.UndeleteQueueRequest]) (*connect.Response[queue.UndeleteQueueResponse], error) {
	return c.undeleteQueue.CallUnary(ctx, req)
}

// ResolveQueue calls cloudidl.queue.QueueService.ResolveQueue.
func (c *queueServiceClient) ResolveQueue(ctx context.Context, req *connect.Request[queue.ResolveQueueRequest]) (*connect.Response[queue.ResolveQueueResponse], error) {
	return c.resolveQueue.CallUnary(ctx, req)
}

// QueueServiceHandler is an implementation of the cloudidl.queue.QueueService service.
type QueueServiceHandler interface {
	// Create or update a queue.
	// A queue cannot take the name of an existing cluster: that name belongs to the cluster's
	// own implicit queue (see ClusterService.CreateCluster).
	CreateQueue(context.Context, *connect.Request[queue.CreateQueueRequest]) (*connect.Response[queue.CreateQueueResponse], error)
	// Update queue spec fully replaces existing spec.
	// A cluster's co-named implicit queue is the exception: its clusters and cluster pool are
	// managed by that cluster and any request changing either is rejected. Its other fields
	// (concurrency, depth, priority, fairness) stay editable.
	// Does not partially update only set fields!
	// Client is expected to get entire spec using GetQueue method, update desired fields and
	// then provide entire spec in UpdateQueue.
	UpdateQueue(context.Context, *connect.Request[queue.UpdateQueueRequest]) (*connect.Response[queue.UpdateQueueResponse], error)
	// Get a queue by name.
	// Soft-deleted queues are returned too, carrying Queue.deleted_at, so a deleted
	// queue's details stay reachable (e.g. from a run that once targeted it).
	GetQueue(context.Context, *connect.Request[queue.GetQueueRequest]) (*connect.Response[queue.GetQueueResponse], error)
	// Update queue status (drain / activate).
	UpdateQueueState(context.Context, *connect.Request[queue.UpdateQueueStateRequest]) (*connect.Response[queue.UpdateQueueStateResponse], error)
	// List queues within a scope.
	// Soft-deleted queues are excluded unless the request filters on the deleted_at field:
	// function EXISTS lists only soft-deleted queues (the only queues that carry
	// Queue.deleted_at), function NOT_EXISTS is the default of live queues only.
	// This is how a client discovers a deleted queue to pass to UndeleteQueue.
	ListQueues(context.Context, *connect.Request[queue.ListQueuesRequest]) (*connect.Response[queue.ListQueuesResponse], error)
	// Stream real-time queue metrics.
	// This endpoint proxies metrics from leasor's QueueManager via internal API.
	WatchQueueMetrics(context.Context, *connect.Request[queue.WatchQueueMetricsRequest], *connect.ServerStream[queue.WatchQueueMetricsResponse]) error
	// Soft-delete a queue: the record is kept but marked as deleted, so the queue
	// disappears from ResolveQueue (unless include_deleted is set) and from ListQueues.
	// ListQueues can explicitly ask for deleted queues, and GetQueue keeps returning the
	// queue with deleted_at set. A deleted queue is no longer scheduled on.
	// The queue must be in DRAINED state, otherwise the request is rejected: drain it
	// with UpdateQueueState first.
	// A soft-deleted queue keeps its name reserved: CreateQueue with the same name is
	// rejected as already existing until the queue is undeleted.
	// Deleting an already deleted queue is rejected.
	// A queue that is referenced as run.default_queue in settings at any scope cannot be
	// deleted until those settings are updated or unset.
	// The reserved "default" queue is no exception: it can be drained and deleted like any
	// other queue — deleting it is how the reserved "default" pool is emptied of live queues
	// so that the pool itself can be deleted (see ClusterPoolService.Delete). While it is
	// deleted, runs that would fall back to it (no queue named and no run.default_queue
	// setting) are rejected at creation. Nothing re-creates it implicitly; UndeleteQueue
	// brings it back.
	// A cluster's co-named implicit queue may be deleted while its cluster is still live, and
	// is also deleted automatically when the cluster is (see ClusterService.DeleteCluster).
	DeleteQueue(context.Context, *connect.Request[queue.DeleteQueueRequest]) (*connect.Response[queue.DeleteQueueResponse], error)
	// Undelete removes the deletion mark from a soft-deleted queue, effectively re-creating
	// it with the spec it had when it was deleted. The queue comes back in DRAINED state and
	// has to be activated with UpdateQueueState to accept work again.
	// Every cluster the queue routes to must be live and in the queue's cluster pool, and the
	// pool itself must be live — a restored queue must never point at something that is gone.
	// For a cluster's co-named queue that means the cluster has to be undeleted instead, which
	// brings the queue back with it (see ClusterService.UndeleteCluster).
	// Undeleting a queue that is not deleted is rejected.
	UndeleteQueue(context.Context, *connect.Request[queue.UndeleteQueueRequest]) (*connect.Response[queue.UndeleteQueueResponse], error)
	// Return the most narrow-scoped queue for given domain, project and queue name.
	// Today, queue name is unique within an org, but we may lift this requirement
	// and have multiple queues with same name, but different scopes in future.
	// Soft-deleted queues resolve to NotFound unless include_deleted is set.
	ResolveQueue(context.Context, *connect.Request[queue.ResolveQueueRequest]) (*connect.Response[queue.ResolveQueueResponse], error)
}

// NewQueueServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewQueueServiceHandler(svc QueueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	queueServiceCreateQueueHandler := connect.NewUnaryHandler(
		QueueServiceCreateQueueProcedure,
		svc.CreateQueue,
		connect.WithSchema(queueServiceCreateQueueMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceUpdateQueueHandler := connect.NewUnaryHandler(
		QueueServiceUpdateQueueProcedure,
		svc.UpdateQueue,
		connect.WithSchema(queueServiceUpdateQueueMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceGetQueueHandler := connect.NewUnaryHandler(
		QueueServiceGetQueueProcedure,
		svc.GetQueue,
		connect.WithSchema(queueServiceGetQueueMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceUpdateQueueStateHandler := connect.NewUnaryHandler(
		QueueServiceUpdateQueueStateProcedure,
		svc.UpdateQueueState,
		connect.WithSchema(queueServiceUpdateQueueStateMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceListQueuesHandler := connect.NewUnaryHandler(
		QueueServiceListQueuesProcedure,
		svc.ListQueues,
		connect.WithSchema(queueServiceListQueuesMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceWatchQueueMetricsHandler := connect.NewServerStreamHandler(
		QueueServiceWatchQueueMetricsProcedure,
		svc.WatchQueueMetrics,
		connect.WithSchema(queueServiceWatchQueueMetricsMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceDeleteQueueHandler := connect.NewUnaryHandler(
		QueueServiceDeleteQueueProcedure,
		svc.DeleteQueue,
		connect.WithSchema(queueServiceDeleteQueueMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceUndeleteQueueHandler := connect.NewUnaryHandler(
		QueueServiceUndeleteQueueProcedure,
		svc.UndeleteQueue,
		connect.WithSchema(queueServiceUndeleteQueueMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	queueServiceResolveQueueHandler := connect.NewUnaryHandler(
		QueueServiceResolveQueueProcedure,
		svc.ResolveQueue,
		connect.WithSchema(queueServiceResolveQueueMethodDescriptor),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/cloudidl.queue.QueueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case QueueServiceCreateQueueProcedure:
			queueServiceCreateQueueHandler.ServeHTTP(w, r)
		case QueueServiceUpdateQueueProcedure:
			queueServiceUpdateQueueHandler.ServeHTTP(w, r)
		case QueueServiceGetQueueProcedure:
			queueServiceGetQueueHandler.ServeHTTP(w, r)
		case QueueServiceUpdateQueueStateProcedure:
			queueServiceUpdateQueueStateHandler.ServeHTTP(w, r)
		case QueueServiceListQueuesProcedure:
			queueServiceListQueuesHandler.ServeHTTP(w, r)
		case QueueServiceWatchQueueMetricsProcedure:
			queueServiceWatchQueueMetricsHandler.ServeHTTP(w, r)
		case QueueServiceDeleteQueueProcedure:
			queueServiceDeleteQueueHandler.ServeHTTP(w, r)
		case QueueServiceUndeleteQueueProcedure:
			queueServiceUndeleteQueueHandler.ServeHTTP(w, r)
		case QueueServiceResolveQueueProcedure:
			queueServiceResolveQueueHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedQueueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedQueueServiceHandler struct{}

func (UnimplementedQueueServiceHandler) CreateQueue(context.Context, *connect.Request[queue.CreateQueueRequest]) (*connect.Response[queue.CreateQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.CreateQueue is not implemented"))
}

func (UnimplementedQueueServiceHandler) UpdateQueue(context.Context, *connect.Request[queue.UpdateQueueRequest]) (*connect.Response[queue.UpdateQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.UpdateQueue is not implemented"))
}

func (UnimplementedQueueServiceHandler) GetQueue(context.Context, *connect.Request[queue.GetQueueRequest]) (*connect.Response[queue.GetQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.GetQueue is not implemented"))
}

func (UnimplementedQueueServiceHandler) UpdateQueueState(context.Context, *connect.Request[queue.UpdateQueueStateRequest]) (*connect.Response[queue.UpdateQueueStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.UpdateQueueState is not implemented"))
}

func (UnimplementedQueueServiceHandler) ListQueues(context.Context, *connect.Request[queue.ListQueuesRequest]) (*connect.Response[queue.ListQueuesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.ListQueues is not implemented"))
}

func (UnimplementedQueueServiceHandler) WatchQueueMetrics(context.Context, *connect.Request[queue.WatchQueueMetricsRequest], *connect.ServerStream[queue.WatchQueueMetricsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.WatchQueueMetrics is not implemented"))
}

func (UnimplementedQueueServiceHandler) DeleteQueue(context.Context, *connect.Request[queue.DeleteQueueRequest]) (*connect.Response[queue.DeleteQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.DeleteQueue is not implemented"))
}

func (UnimplementedQueueServiceHandler) UndeleteQueue(context.Context, *connect.Request[queue.UndeleteQueueRequest]) (*connect.Response[queue.UndeleteQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.UndeleteQueue is not implemented"))
}

func (UnimplementedQueueServiceHandler) ResolveQueue(context.Context, *connect.Request[queue.ResolveQueueRequest]) (*connect.Response[queue.ResolveQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cloudidl.queue.QueueService.ResolveQueue is not implemented"))
}
